name: phone_book
description: "Phone book Web App"

publish_to: 'none' #


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  yaml: ^3.1.2 
  supabase_flutter: ^2.8.4
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/config.yaml
    - assets/darvin.png
